name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      PATH_GITHUB_PACKAGES: docker.pkg.github.com 

    steps:
      
    - uses: actions/checkout@v2
    
    - run: echo "PATH_GITHUB_PACKAGES = $PATH_GITHUB_PACKAGES"
      
    - name: Autenticando no GitHub Packages
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login $PATH_GITHUB_PACKAGES -u renatogroffe --password-stdin
        docker images
