name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      PATH_GITHUB_PACKAGES: docker.pkg.github.com
      NOME_IMAGEM: site-live

    steps:
    - uses: actions/checkout@v2
      
    - name: Autenticando no GitHub Packages
      run: |
        echo "GitHub Packages = $PATH_GITHUB_PACKAGES"
        echo ${{ secrets.GITHUB_TOKEN }} | docker login $PATH_GITHUB_PACKAGES -u renatogroffe --password-stdin
      
    - name: Build e Push das imagens Docker no GitHub Packages
      run: |
        owner_Repository=$GITHUB_REPOSITORY
        owner_Repository=${owner_Repository,,}        
        docker build . --file Dockerfile --tag $PATH_GITHUB_PACKAGES/$owner_Repository/$NOME_IMAGEM:latest
        docker tag $PATH_GITHUB_PACKAGES/$owner_Repository/$NOME_IMAGEM:latest $PATH_GITHUB_PACKAGES/$owner_Repository/$NOME_IMAGEM:$GITHUB_RUN_NUMBER
        docker push $PATH_GITHUB_PACKAGES/$owner_Repository/$NOME_IMAGEM
