name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      PATH_GITHUB_PACKAGES: docker.pkg.github.com

    steps:
      
    - uses: actions/checkout@v2
      
    - name: Autenticando no GitHub Packages
      run: |
        echo "GitHub Packages = $PATH_GITHUB_PACKAGES"
        echo ${{ secrets.GITHUB_TOKEN }} | docker login $PATH_GITHUB_PACKAGES -u renatogroffe --password-stdin
        
    - name: Build e Push das imagens Docker no GitHub Packages
      run: |
        docker build . --file Dockerfile --tag $PATH_GITHUB_PACKAGES/$GITHUB_REPOSITORY/${{ secrets.NOME_IMAGEM }}:$GITHUB_RUN_NUMBER
        docker tag $PATH_GITHUB_PACKAGES/$GITHUB_REPOSITORY/${{ secrets.NOME_IMAGEM }}:$GITHUB_RUN_NUMBER $PATH_GITHUB_PACKAGES/$GITHUB_REPOSITORY/${{ secrets.NOME_IMAGEM }}:latest
        docker push $PATH_GITHUB_PACKAGES/$GITHUB_REPOSITORY/${{ secrets.NOME_IMAGEM }}
